# ==== \ud328\ud0a4\uc9c0/\ubaa8\ub4c8 ====
pkg.up=www
pkg.middle=api/hhd
pkg.down=household
pkg.middle.in=hhd.household
maxUp_pkg_name=www/api/hhd/household
service.name=Household
screen.title=\uac00\uac8c\ubd80
db.table=household
db.key=HOUSEHOLD_IDX


service_templat_name=Template
template_do_path=/www/api/smp/sample

# ==== \uba85\uba85/\ubb38\uad6c ====

unit.biz=basic
author=\uc815\uc9c0\uade0
function.desc=CRUD

# ==== DB ====
db.type=mysql
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/nfi
db.user=root
db.password=1234