# ==== \ud328\ud0a4\uc9c0/\ubaa8\ub4c8 ====
pkg.up=www
pkg.middle=api/usr
pkg.down=user
pkg.middle.in=usr.user
maxUp_pkg_name=www/api/usr/user
service.name=User
screen.title=\uac8c\uc2dc\ud310 \uc815\uc758
db.table=TB_USER
db.key=USER_ID


service_templat_name=Template
template_do_path=/www/api/smp/sample

# ==== \uba85\uba85/\ubb38\uad6c ====

unit.biz=basic
author=\uc815\uc9c0\uade0
function.desc=CRUD

# ==== DB ====
db.type=mysql
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-338786dd-wlrbs1492-17c7.d.aivencloud.com:13981/CONNECT
db.user=avnadmin
db.password=